name: esa-report-generation-app
services:
- name: web
  source_dir: /
  github:
    repo: justinmartin/esa_report_generation_app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  routes:
  - path: /
  http_port: 8080